"""Fourier pseudo-spectral solver with RK4 time integration.

Derivatives are computed exactly in wavenumber space, giving spectral
accuracy in the interior. The target solution is NOT periodic on the unit
square, so a sponge-layer relaxation drives the near-boundary region
toward the analytic solution and damps the Gibbs oscillations that
non-periodicity would otherwise inject. Interior accuracy is unaffected.

The 2/3 dealiasing rule removes the aliasing error generated by the
quadratic u*u_x nonlinearity.
"""
import numpy as np
import burgers2d_common as B


def _sponge_mask(X, Y, width=0.08, strength=50.0):
    """Smooth relaxation coefficient, zero in the interior."""
    d = np.minimum.reduce([X, 1.0 - X, Y, 1.0 - Y])
    m = np.clip(1.0 - d / width, 0.0, 1.0)
    return strength * m**2


def solve_spectral(n=128, t_end=1.0, nu=B.NU_DEFAULT, dt=2e-4,
                   save_times=(0.0, 0.25, 0.5, 0.75, 1.0),
                   sponge_width=0.08, sponge_strength=50.0):
    """Return (x, y, snapshots) with snapshots[t] = (u, v)."""
    x = np.linspace(0.0, 1.0, n, endpoint=False)
    y = np.linspace(0.0, 1.0, n, endpoint=False)
    X, Y = np.meshgrid(x, y, indexing="ij")

    kx = 2.0 * np.pi * np.fft.fftfreq(n, d=1.0 / n)
    ky = 2.0 * np.pi * np.fft.fftfreq(n, d=1.0 / n)
    KX, KY = np.meshgrid(kx, ky, indexing="ij")
    K2 = KX**2 + KY**2

    # 2/3 dealiasing filter.
    kcut = (2.0 / 3.0) * (np.pi * n)
    dealias = (np.abs(KX) < kcut) & (np.abs(KY) < kcut)

    sponge = _sponge_mask(X, Y, sponge_width, sponge_strength)

    def dx_(f):
        return np.real(np.fft.ifft2(1j * KX * np.fft.fft2(f) * dealias))

    def dy_(f):
        return np.real(np.fft.ifft2(1j * KY * np.fft.fft2(f) * dealias))

    def lap_(f):
        return np.real(np.fft.ifft2(-K2 * np.fft.fft2(f) * dealias))

    def rhs(u, v, t):
        ue, ve = B.exact_uv(X, Y, np.full_like(X, t), nu)
        du = (-u * dx_(u) - v * dy_(u) + nu * lap_(u) + sponge * (ue - u))
        dv = (-u * dx_(v) - v * dy_(v) + nu * lap_(v) + sponge * (ve - v))
        return du, dv

    u, v = B.exact_uv(X, Y, np.zeros_like(X), nu)
    u, v = u.copy(), v.copy()

    nt = int(np.ceil(t_end / dt))
    dt = t_end / nt

    snaps, targets = {}, sorted(save_times)
    if targets and targets[0] == 0.0:
        snaps[0.0] = (u.copy(), v.copy())
        targets = targets[1:]

    t = 0.0
    for _ in range(nt):
        k1u, k1v = rhs(u, v, t)
        k2u, k2v = rhs(u + 0.5 * dt * k1u, v + 0.5 * dt * k1v, t + 0.5 * dt)
        k3u, k3v = rhs(u + 0.5 * dt * k2u, v + 0.5 * dt * k2v, t + 0.5 * dt)
        k4u, k4v = rhs(u + dt * k3u, v + dt * k3v, t + dt)

        u = u + (dt / 6.0) * (k1u + 2 * k2u + 2 * k3u + k4u)
        v = v + (dt / 6.0) * (k1v + 2 * k2v + 2 * k3v + k4v)
        t += dt

        while targets and t >= targets[0] - 0.5 * dt:
            snaps[targets[0]] = (u.copy(), v.copy())
            targets = targets[1:]

    return x, y, snaps
